spring:
  sql:
    init:
      mode: never

# JWT Configuration for test environment
jwt:
  expiration:
    minutes: 60
  secret:
    key: aG9sYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWE=

# Default role configuration
default:
  role: EMPLOYEE
